// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	smithydocument "github.com/aws/smithy-go/document"
	"time"
)

// A summary view of an application.
type ApplicationSummary struct {

	// ARN of the resource.
	//
	// This member is required.
	Arn *string

	// The time this resource was created. Timestamps are in ISO8601 format.
	CreatedAt *time.Time

	// Descriptive label for the resource, not a unique ID.
	Description *string

	// GameCast resource ID, base62 encoded.
	Id *string

	// The last time this resource was updated. Timestamps are in ISO8601 format.
	LastUpdatedAt *time.Time

	// A list of valid statuses for Application resource.
	Status ApplicationStatus

	noSmithyDocumentSerde
}

// Information about default application running on the stream group.
type DefaultApplication struct {

	// ARN of the resource.
	Arn *string

	// GameCast resource ID, base62 encoded.
	Id *string

	noSmithyDocumentSerde
}

// Runtime environment is a combination of Windows compatibility layer and other
// graphics libraries used to run the application.
type RuntimeEnvironment struct {

	// Type of the runtime environment used to run games.
	//
	// This member is required.
	Type RuntimeEnvironmentType

	// Versioned container environment used to run customer game. Each runtime fixed
	// version of the Windows compatibility layer to provide a stable game performance.
	//
	// This member is required.
	Version *string

	noSmithyDocumentSerde
}

// Application save configuration
type SaveConfiguration struct {

	// A list of save file, registry key or log paths that are absolute paths that
	// store game save files when the games are running on a Windows environment.
	FileLocations []string

	// A list of save file, registry key or log paths that are absolute paths that
	// store game save files when the games are running on a Windows environment.
	RegistryLocations []string

	noSmithyDocumentSerde
}

// A summary view of a stream group.
type StreamGroupSummary struct {

	// ARN of the resource.
	//
	// This member is required.
	Arn *string

	// The time this resource was created. Timestamps are in ISO8601 format.
	CreatedAt *time.Time

	// Information about default application running on the stream group.
	DefaultApplication *DefaultApplication

	// Descriptive label for the resource, not a unique ID.
	Description *string

	// GameCast resource ID, base62 encoded.
	Id *string

	// The last time this resource was updated. Timestamps are in ISO8601 format.
	LastUpdatedAt *time.Time

	// A list of valid statuses for Stream Group resource.
	Status StreamGroupStatus

	// These are pre-packed virtual instance type used to run customer games where
	// mini spec maps to high-end integrated graphics and ultra maps to high-end gaming
	// pc. These have different cost implications.
	StreamClass StreamClass

	noSmithyDocumentSerde
}

// A summary view of stream session.
type StreamSessionSummary struct {

	// ARN of the resource.
	Arn *string

	// The time this resource was created. Timestamps are in ISO8601 format.
	CreatedAt *time.Time

	// The last time this resource was updated. Timestamps are in ISO8601 format.
	LastUpdatedAt *time.Time

	// The streaming protocol. Only WebRTC for now.
	Protocol Protocol

	// A list of valid statuses for Stream Session.
	Status StreamSessionStatus

	// GameCast resource ID, base62 encoded.
	StreamGroupId *string

	// Opaque unique user ID to maintain game saved data.
	UserId *string

	noSmithyDocumentSerde
}

// Stores information about a field passed inside a request that resulted in an
// exception.
type ValidationExceptionField struct {

	// Detailed error message
	//
	// This member is required.
	Message *string

	// Name of the field that caused the Validation Exception.
	//
	// This member is required.
	Name *string

	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde
