// Code generated by smithy-go-codegen DO NOT EDIT.

// Package gamecast provides the API client, operations, and parameter types for
// AmazonGameCast.
//
// Amazon GameCast is a new AWS service that enables customers to build their own
// game streaming experience.
package gamecast
