// Code generated by internal/repotools/cmd/updatemodulemeta DO NOT EDIT.

package gamecast

// goModuleVersion is the tagged release for this module
const goModuleVersion = "1.0.0-zeta.2f8abba842e3"
